language: java
before_install:
- sudo apt-get update
- sudo apt-get install sshpass
install: mvn install
jdk:
- oraclejdk8
env:
  global:
  - secure: B2E28tmbaIugF17J1lfzbphTt4jdc90kxRUf8Z61L89FU7xI6mOrBlrpcRm1j1qmJW2OWtHGF8D+nLCQ9a2VXrjyLeW691avO+e+XbGVhIGecj5VQA9Duwj9entneIKbI+zQt71nd6OHbICmWUha2yLlCNMN5aYmlDFsnk+6tsJAFLTw/NFPl7lTf6ZPoiYAOSQJjKEkZPH9bqQHofZw+Yk5kiZU3+oOMJVnsCoWO6J2FynpztMu6ydhKheaJISF6Vj1MYEJ0YmcUldphJEQ7vAB2uDBR0JvIcYRuE9DJbiur3Z7qDzyzi7gSvdfVh++dopqTnM56K/TBHlx8c/S9uYrJFqRkgYt9kMZhP/UqywP25955cUVQvsOiJ9p7vdjpd0YYMXMVz6dKFeKTjPqzX6ttrPGVvbzumjOMPxquJIQ41k/WKoAA445vXS2i2icL+FOTLzP58nNCkt1PgEsaVnckpvlyB6WsHVUz4/wwqWWA9oKx1DLHxdaaLRWhcFI5aCccsTj7HUC0RG16rHpPY3GVHfqf3blxnNob0AQnJlb7Q3yqmy8AnlC1E4BrWgaxHWwM/WGXObpk0MvppiQN0hYuJKO+cIlLbVh6VGXlg+gaSCZFK50cCv7EkM/S6JVW0sPARtZUZSpr9paoe2tSJjtrKdVLhAiQtOKMqT0WIY=
  - secure: vunbqvyFvMP8CqUcFH40Gp7wB47KlKXGiIs+plzGWZVDYVLhiFwxvUYzsIIbEyatWXICuNRiBFIR8GODKY+dQgHXtDxbGvAmCzuRCxIwvAfEJg+58QUldX4/FgtV6drSbuMFcRAtM/fFIQKE/ONahvUNMWvrCA/eGM5cFtH8eFF1PmV8vF0AFHvP9Gzqk/0vJu0B/KNOFzA68UhysSpNp4FsRBSEGO+cUU5eblLSM3rsnDPCPH+u1Adw7+3v8uwlieMLIm8FoMrHYN3OEboSYF7/OnIIswGUjLklPfWqEVP5f70N+nLmw2Pz2JqeAz5hegrDYq7WAIT9hT93wL3XnzD6iZTZWwu0Vw0aCBO8GH5YZgE0EaP9jq/D6MZyPkK4aRa7e4qkqaK2LvbA1lih6CcDY72stZ36uVZBKCXo7tgU0HvxBTz+e1zkp157IfpxVtjwsMR0cG8ZCCplDUgxwdxxkKmZj6prIJnLT3VX+nmil9vfSa+eO6orgmfwKCSxtdWwkYnQ0T3qv4P9bKrJLpPq3vtAOeRqPQR2Wj6j1eOkXMpOAbixcWgYXdBlhjsg2wYj1wG1hbys+RyyXOiPUV9jAGd4ObTm2lGFIkULP5Rj9r/OtabEUp55/803bjRpZ9raExeEOl4PlyoqX0v3+rTh8tl+kMGkO2q5mkP2AiA=
after_success:
- sshpass -p "$password" ssh -o StrictHostKeyChecking=no travis@$IP pkill java
- sshpass -p "$password" scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  target/*.jar travis@$IP:/home/travis
- sshpass -p "$password" ssh -o StrictHostKeyChecking=no travis@$IP java -jar *.jar
